apiVersion: v1
kind: ServiceAccount
metadata:
  name: xploreml-sa
  namespace: xploreml
  labels:
    app: xploreml
    component: auth
  annotations:
    iam.gke.io/gcp-service-account: xploreml-sa@YOUR_PROJECT_ID.iam.gserviceaccount.com
---
